apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ry4li7vpb-go 
  janus-idp.io/tekton: ry4li7vpb-go
  backstage.io/kubernetes-id: ry4li7vpb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ry4li7vpb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml